Deploy Yjs and Writes examples

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -85,6 +85,30 @@ jobs:
             exit 123
           fi
 
+      - name: Deploy yjs example
+        working-directory: ./examples/yjs
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            yjs=$(jq -r '.website' .sst/outputs.json)
+            echo "yjs=$yjs" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
+      - name: Deploy Write Patterns example
+        working-directory: ./examples/write-patterns
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            writes=$(jq -r '.website' .sst/outputs.json)
+            echo "writes=$writes" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
       - name: Add comment to PR
         if: github.event_name == 'pull_request'
         uses: actions/github-script@v7
@@ -94,12 +118,15 @@ jobs:
             const linearlite_read_only = process.env.linearlite_read_only;
             const nextjs = process.env.nextjs;
             const todoapp = process.env.todoapp;
+            const yjs = process.env.yjs;
+            const writes = process.env.writes;
 
             const prNumber = context.issue.number;
             const commentBody = `## Examples
             - linearlite-read-only: ${linearlite_read_only}
             - nextjs: ${nextjs}
             - todoapp: ${todoapp}
+            - yjs: ${yjs}
             `;
 
             const { data: comments } = await github.rest.issues.listComments({
