Update todo example

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -101,17 +101,18 @@ jobs:
       #       exit 123
       #     fi
 
-      # - name: Deploy TODO App example
-      #   working-directory: ./examples/todo-app
-      #   run: |
-      #     pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-      #     if [ -f ".sst/outputs.json" ]; then
-      #       todoapp=$(jq -r '.website' .sst/outputs.json)
-      #       echo "todoapp=$todoapp" >> $GITHUB_ENV
-      #     else
-      #       echo "sst outputs file not found. Exiting."
-      #       exit 123
-      #     fi
+      - name: Deploy TODO App example
+        working-directory: ./examples/todo-app
+        continue-on-error: true
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            todoapp=$(jq -r '.website' .sst/outputs.json)
+            echo "todoapp=$todoapp" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
 
       # - name: Deploy proxy-auth example
       #   working-directory: ./examples/proxy-auth
