small improvements

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -51,20 +51,6 @@ jobs:
           restore-keys: |
             sst-cache-main-${{ runner.os }}
 
-      - name: Deploy Linearlite Read Only
-        working-directory: ./examples/linearlite-read-only
-        run: |
-          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-          code=$!
-          if [ -f ".sst/outputs.json" ]; then
-            linearlite_read_only=$(jq -r '.website' .sst/outputs.json)
-            echo "linearlite_read_only=$linearlite_read_only" >> $GITHUB_ENV
-          else
-            echo "sst outputs file not found. Exiting."
-            exit 123
-          fi
-          exit $code
-
       - name: Deploy Yjs example
         working-directory: ./examples/yjs
         run: |
@@ -73,6 +59,20 @@ jobs:
           if [ -f ".sst/outputs.json" ]; then
             yjs=$(jq -r '.website' .sst/outputs.json)
             echo "yjs=$yjs" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+          exit $code
+
+      - name: Deploy Linearlite Read Only
+        working-directory: ./examples/linearlite-read-only
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
+          if [ -f ".sst/outputs.json" ]; then
+            linearlite_read_only=$(jq -r '.website' .sst/outputs.json)
+            echo "linearlite_read_only=$linearlite_read_only" >> $GITHUB_ENV
           else
             echo "sst outputs file not found. Exiting."
             exit 123
