Minor fixes

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -56,24 +56,30 @@ jobs:
         continue-on-error: true
         run: |
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
           if [ -f ".sst/outputs.json" ]; then
             yjs=$(jq -r '.website' .sst/outputs.json)
             echo "yjs=$yjs" >> $GITHUB_ENV
           else
             echo "sst outputs file not found. Exiting."
+            exit 123
           fi
+          exit $code
 
-      # - name: Deploy Linearlite Read Only
-      #   working-directory: ./examples/linearlite-read-only
-      #   run: |
-      #     pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-      #     if [ -f ".sst/outputs.json" ]; then
-      #       linearlite_read_only=$(jq -r '.website' .sst/outputs.json)
-      #       echo "linearlite_read_only=$linearlite_read_only" >> $GITHUB_ENV
-      #     else
-      #       echo "sst outputs file not found. Exiting."
-      #       exit 123
-      #     fi
+      - name: Deploy Linearlite Read Only
+        working-directory: ./examples/linearlite-read-only
+        continue-on-error: true
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
+          if [ -f ".sst/outputs.json" ]; then
+            linearlite_read_only=$(jq -r '.website' .sst/outputs.json)
+            echo "linearlite_read_only=$linearlite_read_only" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+          exit $code
 
       - name: Deploy Write Patterns example
         working-directory: ./examples/write-patterns
@@ -81,6 +87,7 @@ jobs:
         run: |
           pnpm --filter @electric-sql/client --filter @electric-sql/experimental --filter @electric-sql/react run build
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
           if [ -f ".sst/outputs.json" ]; then
             writes=$(jq -r '.website' .sst/outputs.json)
             echo "writes=$writes" >> $GITHUB_ENV
@@ -88,24 +95,29 @@ jobs:
             echo "sst outputs file not found. Exiting."
             exit 123
           fi
+          exit $code
 
-      # - name: Deploy NextJs example
-      #   working-directory: ./examples/nextjs
-      #   run: |
-      #     pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-      #     if [ -f ".sst/outputs.json" ]; then
-      #       nextjs=$(jq -r '.website' .sst/outputs.json)
-      #       echo "nextjs=$nextjs" >> $GITHUB_ENV
-      #     else
-      #       echo "sst outputs file not found. Exiting."
-      #       exit 123
-      #     fi
+      - name: Deploy NextJs example
+        working-directory: ./examples/nextjs
+        continue-on-error: true
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
+          if [ -f ".sst/outputs.json" ]; then
+            nextjs=$(jq -r '.website' .sst/outputs.json)
+            echo "nextjs=$nextjs" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+          exit $code
 
       - name: Deploy TODO App example
         working-directory: ./examples/todo-app
         continue-on-error: true
         run: |
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
           if [ -f ".sst/outputs.json" ]; then
             todoapp=$(jq -r '.website' .sst/outputs.json)
             echo "todoapp=$todoapp" >> $GITHUB_ENV
@@ -113,12 +125,14 @@ jobs:
             echo "sst outputs file not found. Exiting."
             exit 123
           fi
+          exit $code
 
       - name: Deploy proxy-auth example
         working-directory: ./examples/proxy-auth
         continue-on-error: true
         run: |
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          code=$!
           if [ -f ".sst/outputs.json" ]; then
             auth=$(jq -r '.website' .sst/outputs.json)
             echo "auth=$auth" >> $GITHUB_ENV
@@ -126,6 +140,7 @@ jobs:
             echo "sst outputs file not found. Exiting."
             exit 123
           fi
+          exit $code
 
       - name: Add comment to PR
         if: github.event_name == 'pull_request'
