Remaining examples

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -61,6 +61,18 @@ jobs:
             exit 123
           fi
 
+      - name: Deploy Linearlite
+        working-directory: ./examples/linearlite
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+              linearlite=$(jq -r '.website' .sst/outputs.json)
+              echo "linearlite=$linearlite" >> $GITHUB_ENV
+            else
+              echo "sst outputs file not found. Exiting."
+              exit 123
+            fi
+
       - name: Deploy NextJs example
         working-directory: ./examples/nextjs
         run: |
@@ -85,7 +97,7 @@ jobs:
             exit 123
           fi
 
-      - name: Deploy yjs example
+      - name: Deploy Yjs example
         working-directory: ./examples/yjs
         run: |
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
@@ -109,6 +121,18 @@ jobs:
             exit 123
           fi
 
+      - name: Deploy proxy-auth example
+        working-directory: ./examples/proxy-auth
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            auth=$(jq -r '.website' .sst/outputs.json)
+            echo "auth=$auth" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
       - name: Add comment to PR
         if: github.event_name == 'pull_request'
         uses: actions/github-script@v7
@@ -116,10 +140,12 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const linearlite_read_only = process.env.linearlite_read_only;
+            const linearlite = process.env.linearlite;
             const nextjs = process.env.nextjs;
             const todoapp = process.env.todoapp;
             const yjs = process.env.yjs;
             const writes = process.env.writes;
+            const auth = process.env.auth;
 
             const prNumber = context.issue.number;
             const commentBody = `## Examples
