chore (examples): Add authentication to the examples (#2248)
Updated GH Actions all SST scripts to use the necessary tokens to reach the admin-api

---------

Co-authored-by: Valter Balegas <balegas@electric-sql.com>

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -26,6 +26,8 @@ jobs:
       ELECTRIC_API: ${{ secrets.ELECTRIC_API }}
       ELECTRIC_ADMIN_API: ${{ secrets.ELECTRIC_ADMIN_API }}
       ELECTRIC_TEAM_ID: ${{ secrets.ELECTRIC_TEAM_ID }}
+      ELECTRIC_ADMIN_API_TOKEN_ID: ${{ secrets.ELECTRIC_ADMIN_API_TOKEN_ID }}
+      ELECTRIC_ADMIN_API_TOKEN_SECRET: ${{ secrets.ELECTRIC_ADMIN_API_TOKEN_SECRET }}
       # HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY }} TODO
 
     steps:
@@ -47,6 +49,18 @@ jobs:
           restore-keys: |
             sst-cache-main-${{ runner.os }}
 
+      - name: Deploy Yjs example
+        working-directory: ./examples/yjs
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            yjs=$(jq -r '.website' .sst/outputs.json)
+            echo "yjs=$yjs" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
       - name: Deploy Linearlite Read Only
         working-directory: ./examples/linearlite-read-only
         run: |
@@ -54,6 +68,19 @@ jobs:
           if [ -f ".sst/outputs.json" ]; then
             linearlite_read_only=$(jq -r '.website' .sst/outputs.json)
             echo "linearlite_read_only=$linearlite_read_only" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
+      - name: Deploy Write Patterns example
+        working-directory: ./examples/write-patterns
+        run: |
+          pnpm --filter @electric-sql/client --filter @electric-sql/experimental --filter @electric-sql/react run build
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            writes=$(jq -r '.website' .sst/outputs.json)
+            echo "writes=$writes" >> $GITHUB_ENV
           else
             echo "sst outputs file not found. Exiting."
             exit 123
@@ -71,6 +98,30 @@ jobs:
             exit 123
           fi
 
+      - name: Deploy TODO App example
+        working-directory: ./examples/todo-app
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            todoapp=$(jq -r '.website' .sst/outputs.json)
+            echo "todoapp=$todoapp" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
+      - name: Deploy proxy-auth example
+        working-directory: ./examples/proxy-auth
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            auth=$(jq -r '.website' .sst/outputs.json)
+            echo "auth=$auth" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
       - name: Add comment to PR
         if: github.event_name == 'pull_request'
         uses: actions/github-script@v7
@@ -79,11 +130,19 @@ jobs:
           script: |
             const linearlite_read_only = process.env.linearlite_read_only;
             const nextjs = process.env.nextjs;
+            const todoapp = process.env.todoapp;
+            const yjs = process.env.yjs;
+            const writes = process.env.writes;
+            const auth = process.env.auth;
 
             const prNumber = context.issue.number;
             const commentBody = `## Examples
             - linearlite-read-only: ${linearlite_read_only}
             - nextjs: ${nextjs}
+            - todoapp: ${todoapp}
+            - yjs: ${yjs}
+            - writes: ${writes}
+            - auth: ${auth}
             `;
 
             const { data: comments } = await github.rest.issues.listComments({
