Update write patterns example

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -53,16 +53,15 @@ jobs:
 
       - name: Deploy Yjs example
         working-directory: ./examples/yjs
+        continue-on-error: true
         run: |
           pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-          code=$!
           if [ -f ".sst/outputs.json" ]; then
             yjs=$(jq -r '.website' .sst/outputs.json)
             echo "yjs=$yjs" >> $GITHUB_ENV
           else
             echo "sst outputs file not found. Exiting."
           fi
-          exit $code
 
       # - name: Deploy Linearlite Read Only
       #   working-directory: ./examples/linearlite-read-only
@@ -76,18 +75,19 @@ jobs:
       #       exit 123
       #     fi
 
-      # - name: Deploy Write Patterns example
-      #   working-directory: ./examples/write-patterns
-      #   run: |
-      #     pnpm --filter @electric-sql/client --filter @electric-sql/experimental --filter @electric-sql/react run build
-      #     pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
-      #     if [ -f ".sst/outputs.json" ]; then
-      #       writes=$(jq -r '.website' .sst/outputs.json)
-      #       echo "writes=$writes" >> $GITHUB_ENV
-      #     else
-      #       echo "sst outputs file not found. Exiting."
-      #       exit 123
-      #     fi
+      - name: Deploy Write Patterns example
+        working-directory: ./examples/write-patterns
+        continue-on-error: true
+        run: |
+          pnpm --filter @electric-sql/client --filter @electric-sql/experimental --filter @electric-sql/react run build
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            writes=$(jq -r '.website' .sst/outputs.json)
+            echo "writes=$writes" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
 
       # - name: Deploy NextJs example
       #   working-directory: ./examples/nextjs
