Add comment with links to deployed examples

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -50,8 +50,64 @@ jobs:
 
       - name: Deploy Linearlite
         working-directory: examples/linearlite
-        run: pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            linearlite=$(jq -r '.website' .sst/outputs.json)
+            echo "linearlite=$linearlite" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 1
+          fi
+
 
       - name: Deploy NextJs example
         working-directory: examples/nextjs-example
-        run: pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            nextjs=$(jq -r '.website' .sst/outputs.json)
+            echo "nextjs=$nextjs" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 1
+          fi
+
+      - name: Add comment to PR
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const linearlite = process.env.linearlite;
+            const nextjs = process.env.nextjs;
+            const commentBody = `## Examples
+            - linearlite: ${linearlite}
+            - nextjs: ${nextjs}
+            `;
+
+            const { data: comments } = await github.rest.issues.listComments({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: prNumber,
+            });
+
+            const existingComment = comments.find(comment => comment.user.login ==='github-actions[bot]' && comment.body.startsWith("## Examples"));
+
+            if (existingComment) {
+              // Update the existing comment
+              await github.rest.issues.updateComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                comment_id: existingComment.id,
+                body: commentBody,
+              });
+            } else {
+              // Create a new comment if none exists
+              await github.rest.issues.createComment({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                issue_number: prNumber,
+                body: commentBody,
+              });
+            }
+
