Deploy linearlite-read-only, nextjs, todoapp

diff --git a/.github/workflows/deploy_examples.yml b/.github/workflows/deploy_examples.yml
--- a/.github/workflows/deploy_examples.yml
+++ b/.github/workflows/deploy_examples.yml
@@ -73,6 +73,18 @@ jobs:
             exit 123
           fi
 
+      - name: Deploy TODO App example
+        working-directory: ./examples/todo-app
+        run: |
+          pnpm sst deploy --stage ${{ env.DEPLOY_ENV }}
+          if [ -f ".sst/outputs.json" ]; then
+            todoapp=$(jq -r '.website' .sst/outputs.json)
+            echo "todoapp=$todoapp" >> $GITHUB_ENV
+          else
+            echo "sst outputs file not found. Exiting."
+            exit 123
+          fi
+
       - name: Add comment to PR
         if: github.event_name == 'pull_request'
         uses: actions/github-script@v7
@@ -81,11 +93,13 @@ jobs:
           script: |
             const linearlite_read_only = process.env.linearlite_read_only;
             const nextjs = process.env.nextjs;
+            const todoapp = process.env.todoapp;
 
             const prNumber = context.issue.number;
             const commentBody = `## Examples
             - linearlite-read-only: ${linearlite_read_only}
             - nextjs: ${nextjs}
+            - todoapp: ${todoapp}
             `;
 
             const { data: comments } = await github.rest.issues.listComments({
